language: java
jdk: oraclejdk8

sudo: required

notifications:
  email:
    recipients:
      - techragesh@gmail.com
    on_success: never
    on_failure: always

after_success:
  - bash <(curl -s https://codecov.io/bash)